/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "D:\\study\\gitbook\\node_modules\\@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-21ce7b79",
    path: "/Axios/Axios.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-21ce7b79").then(next)
    },
  },
  {
    name: "v-e8e33b10",
    path: "/Docker/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-e8e33b10").then(next)
    },
  },
  {
    path: "/Docker/index.html",
    redirect: "/Docker/"
  },
  {
    name: "v-6b962f9a",
    path: "/Docker/docker.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6b962f9a").then(next)
    },
  },
  {
    name: "v-4befb6bc",
    path: "/Git/Git%20SSH.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4befb6bc").then(next)
    },
  },
  {
    path: "/Git/Git SSH.html",
    redirect: "/Git/Git%20SSH.html"
  },
  {
    path: "/Git/Git SSH.html",
    redirect: "/Git/Git%20SSH.html"
  },
  {
    name: "v-9076552c",
    path: "/Git/Git%20%E7%BB%9F%E8%AE%A1.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-9076552c").then(next)
    },
  },
  {
    path: "/Git/Git 统计.html",
    redirect: "/Git/Git%20%E7%BB%9F%E8%AE%A1.html"
  },
  {
    path: "/Git/Git 统计.html",
    redirect: "/Git/Git%20%E7%BB%9F%E8%AE%A1.html"
  },
  {
    name: "v-1eef2b08",
    path: "/Git/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1eef2b08").then(next)
    },
  },
  {
    path: "/Git/index.html",
    redirect: "/Git/"
  },
  {
    name: "v-85223540",
    path: "/Git/gh-pages%E5%88%86%E6%94%AF%E5%8F%91%E5%B8%83%E9%9D%99%E6%80%81%E9%A1%B9%E7%9B%AE.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-85223540").then(next)
    },
  },
  {
    path: "/Git/gh-pages分支发布静态项目.html",
    redirect: "/Git/gh-pages%E5%88%86%E6%94%AF%E5%8F%91%E5%B8%83%E9%9D%99%E6%80%81%E9%A1%B9%E7%9B%AE.html"
  },
  {
    path: "/Git/gh-pages分支发布静态项目.html",
    redirect: "/Git/gh-pages%E5%88%86%E6%94%AF%E5%8F%91%E5%B8%83%E9%9D%99%E6%80%81%E9%A1%B9%E7%9B%AE.html"
  },
  {
    name: "v-c967673a",
    path: "/Git/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98%E5%8F%8A%E8%A7%A3%E5%86%B3%E6%96%B9%E6%A1%88.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-c967673a").then(next)
    },
  },
  {
    path: "/Git/常见问题及解决方案.html",
    redirect: "/Git/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98%E5%8F%8A%E8%A7%A3%E5%86%B3%E6%96%B9%E6%A1%88.html"
  },
  {
    path: "/Git/常见问题及解决方案.html",
    redirect: "/Git/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98%E5%8F%8A%E8%A7%A3%E5%86%B3%E6%96%B9%E6%A1%88.html"
  },
  {
    name: "v-01f3148e",
    path: "/HTML&&CSS/Table.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-01f3148e").then(next)
    },
  },
  {
    name: "v-ec3396a0",
    path: "/HTML&&CSS/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-ec3396a0").then(next)
    },
  },
  {
    path: "/HTML&&CSS/index.html",
    redirect: "/HTML&&CSS/"
  },
  {
    name: "v-01bc2cf8",
    path: "/HTTP/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-01bc2cf8").then(next)
    },
  },
  {
    path: "/HTTP/index.html",
    redirect: "/HTTP/"
  },
  {
    name: "v-14236aaa",
    path: "/HTTP/%E5%B8%B8%E8%A7%81%E9%94%99%E8%AF%AF%E7%A0%81.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-14236aaa").then(next)
    },
  },
  {
    path: "/HTTP/常见错误码.html",
    redirect: "/HTTP/%E5%B8%B8%E8%A7%81%E9%94%99%E8%AF%AF%E7%A0%81.html"
  },
  {
    path: "/HTTP/常见错误码.html",
    redirect: "/HTTP/%E5%B8%B8%E8%A7%81%E9%94%99%E8%AF%AF%E7%A0%81.html"
  },
  {
    name: "v-1e07e0c5",
    path: "/Java/Java%20%E5%9F%BA%E6%9C%AC%E6%A6%82%E5%BF%B5.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1e07e0c5").then(next)
    },
  },
  {
    path: "/Java/Java 基本概念.html",
    redirect: "/Java/Java%20%E5%9F%BA%E6%9C%AC%E6%A6%82%E5%BF%B5.html"
  },
  {
    path: "/Java/Java 基本概念.html",
    redirect: "/Java/Java%20%E5%9F%BA%E6%9C%AC%E6%A6%82%E5%BF%B5.html"
  },
  {
    name: "v-8d1d9f90",
    path: "/Java/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-8d1d9f90").then(next)
    },
  },
  {
    path: "/Java/index.html",
    redirect: "/Java/"
  },
  {
    name: "v-008d1c5e",
    path: "/JavaScript/Array.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-008d1c5e").then(next)
    },
  },
  {
    name: "v-4a7d791a",
    path: "/JavaScript/Browser.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4a7d791a").then(next)
    },
  },
  {
    name: "v-72658613",
    path: "/JavaScript/Date.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-72658613").then(next)
    },
  },
  {
    name: "v-14c7609a",
    path: "/JavaScript/Ecmascript.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-14c7609a").then(next)
    },
  },
  {
    name: "v-6c0b1f5a",
    path: "/JavaScript/Function.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6c0b1f5a").then(next)
    },
  },
  {
    name: "v-f29100da",
    path: "/JavaScript/Introduction.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-f29100da").then(next)
    },
  },
  {
    name: "v-623e0f5a",
    path: "/JavaScript/JSON.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-623e0f5a").then(next)
    },
  },
  {
    name: "v-581cc044",
    path: "/JavaScript/Javascript%E8%AE%BE%E8%AE%A1%E6%A8%A1%E5%BC%8F.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-581cc044").then(next)
    },
  },
  {
    path: "/JavaScript/Javascript设计模式.html",
    redirect: "/JavaScript/Javascript%E8%AE%BE%E8%AE%A1%E6%A8%A1%E5%BC%8F.html"
  },
  {
    path: "/JavaScript/Javascript设计模式.html",
    redirect: "/JavaScript/Javascript%E8%AE%BE%E8%AE%A1%E6%A8%A1%E5%BC%8F.html"
  },
  {
    name: "v-04e0969a",
    path: "/JavaScript/Number.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-04e0969a").then(next)
    },
  },
  {
    name: "v-e970d21a",
    path: "/JavaScript/Object.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-e970d21a").then(next)
    },
  },
  {
    name: "v-12b1a550",
    path: "/JavaScript/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-12b1a550").then(next)
    },
  },
  {
    path: "/JavaScript/index.html",
    redirect: "/JavaScript/"
  },
  {
    name: "v-310387b3",
    path: "/JavaScript/String.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-310387b3").then(next)
    },
  },
  {
    name: "v-3a3cc8f2",
    path: "/JavaScript/debounce%20&%20throttle.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3a3cc8f2").then(next)
    },
  },
  {
    path: "/JavaScript/debounce & throttle.html",
    redirect: "/JavaScript/debounce%20&%20throttle.html"
  },
  {
    path: "/JavaScript/debounce & throttle.html",
    redirect: "/JavaScript/debounce%20&%20throttle.html"
  },
  {
    name: "v-7c1162a9",
    path: "/JavaScript/webpack.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7c1162a9").then(next)
    },
  },
  {
    name: "v-7ffca630",
    path: "/JavaScript/%E5%B8%B8%E8%A7%81%E5%B7%A5%E5%85%B7%E4%BB%A3%E7%A0%81%E7%89%87%E6%AE%B5.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7ffca630").then(next)
    },
  },
  {
    path: "/JavaScript/常见工具代码片段.html",
    redirect: "/JavaScript/%E5%B8%B8%E8%A7%81%E5%B7%A5%E5%85%B7%E4%BB%A3%E7%A0%81%E7%89%87%E6%AE%B5.html"
  },
  {
    path: "/JavaScript/常见工具代码片段.html",
    redirect: "/JavaScript/%E5%B8%B8%E8%A7%81%E5%B7%A5%E5%85%B7%E4%BB%A3%E7%A0%81%E7%89%87%E6%AE%B5.html"
  },
  {
    name: "v-114baa76",
    path: "/JavaScript/%E5%B8%B8%E8%A7%81%E6%AD%A3%E5%88%99%E8%A1%A8%E8%BE%BE%E5%BC%8F.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-114baa76").then(next)
    },
  },
  {
    path: "/JavaScript/常见正则表达式.html",
    redirect: "/JavaScript/%E5%B8%B8%E8%A7%81%E6%AD%A3%E5%88%99%E8%A1%A8%E8%BE%BE%E5%BC%8F.html"
  },
  {
    path: "/JavaScript/常见正则表达式.html",
    redirect: "/JavaScript/%E5%B8%B8%E8%A7%81%E6%AD%A3%E5%88%99%E8%A1%A8%E8%BE%BE%E5%BC%8F.html"
  },
  {
    name: "v-61712db8",
    path: "/Linux/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-61712db8").then(next)
    },
  },
  {
    path: "/Linux/index.html",
    redirect: "/Linux/"
  },
  {
    name: "v-6395688e",
    path: "/Linux/mingling.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6395688e").then(next)
    },
  },
  {
    name: "v-44b3e8f9",
    path: "/Linux/vim.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-44b3e8f9").then(next)
    },
  },
  {
    name: "v-7ef70638",
    path: "/Nginx/Gzip%20%E5%8E%8B%E7%BC%A9.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7ef70638").then(next)
    },
  },
  {
    path: "/Nginx/Gzip 压缩.html",
    redirect: "/Nginx/Gzip%20%E5%8E%8B%E7%BC%A9.html"
  },
  {
    path: "/Nginx/Gzip 压缩.html",
    redirect: "/Nginx/Gzip%20%E5%8E%8B%E7%BC%A9.html"
  },
  {
    name: "v-0a101ff4",
    path: "/Nginx/Nginx%20%E6%9E%B6%E6%9E%84%E8%AE%BE%E8%AE%A1.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0a101ff4").then(next)
    },
  },
  {
    path: "/Nginx/Nginx 架构设计.html",
    redirect: "/Nginx/Nginx%20%E6%9E%B6%E6%9E%84%E8%AE%BE%E8%AE%A1.html"
  },
  {
    path: "/Nginx/Nginx 架构设计.html",
    redirect: "/Nginx/Nginx%20%E6%9E%B6%E6%9E%84%E8%AE%BE%E8%AE%A1.html"
  },
  {
    name: "v-32c3fdec",
    path: "/Nginx/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-32c3fdec").then(next)
    },
  },
  {
    path: "/Nginx/index.html",
    redirect: "/Nginx/"
  },
  {
    name: "v-1f7b1779",
    path: "/Nginx/Rewrite.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1f7b1779").then(next)
    },
  },
  {
    name: "v-149baafb",
    path: "/Nginx/%E6%8C%87%E4%BB%A4%E5%8F%8A%E5%9F%BA%E6%9C%AC%E4%BB%8B%E7%BB%8D.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-149baafb").then(next)
    },
  },
  {
    path: "/Nginx/指令及基本介绍.html",
    redirect: "/Nginx/%E6%8C%87%E4%BB%A4%E5%8F%8A%E5%9F%BA%E6%9C%AC%E4%BB%8B%E7%BB%8D.html"
  },
  {
    path: "/Nginx/指令及基本介绍.html",
    redirect: "/Nginx/%E6%8C%87%E4%BB%A4%E5%8F%8A%E5%9F%BA%E6%9C%AC%E4%BB%8B%E7%BB%8D.html"
  },
  {
    name: "v-4fb6e082",
    path: "/Nginx/%E6%AD%A3%E5%90%91%E4%BB%A3%E7%90%86%E5%92%8C%E5%8F%8D%E5%90%91%E4%BB%A3%E7%90%86.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-4fb6e082").then(next)
    },
  },
  {
    path: "/Nginx/正向代理和反向代理.html",
    redirect: "/Nginx/%E6%AD%A3%E5%90%91%E4%BB%A3%E7%90%86%E5%92%8C%E5%8F%8D%E5%90%91%E4%BB%A3%E7%90%86.html"
  },
  {
    path: "/Nginx/正向代理和反向代理.html",
    redirect: "/Nginx/%E6%AD%A3%E5%90%91%E4%BB%A3%E7%90%86%E5%92%8C%E5%8F%8D%E5%90%91%E4%BB%A3%E7%90%86.html"
  },
  {
    name: "v-24814f9a",
    path: "/Python/python.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-24814f9a").then(next)
    },
  },
  {
    name: "v-6d1a02f8",
    path: "/Python/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6d1a02f8").then(next)
    },
  },
  {
    path: "/Python/index.html",
    redirect: "/Python/"
  },
  {
    name: "v-7e50d755",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7e50d755").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-14b3f562",
    path: "/React/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-14b3f562").then(next)
    },
  },
  {
    path: "/React/index.html",
    redirect: "/React/"
  },
  {
    name: "v-5aa58d88",
    path: "/React/React%20Hooks.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5aa58d88").then(next)
    },
  },
  {
    path: "/React/React Hooks.html",
    redirect: "/React/React%20Hooks.html"
  },
  {
    path: "/React/React Hooks.html",
    redirect: "/React/React%20Hooks.html"
  },
  {
    name: "v-5eda06f9",
    path: "/React/Route.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-5eda06f9").then(next)
    },
  },
  {
    name: "v-33ab6f10",
    path: "/Window/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-33ab6f10").then(next)
    },
  },
  {
    path: "/Window/index.html",
    redirect: "/Window/"
  },
  {
    name: "v-c51e27f2",
    path: "/Window/window%E7%BB%88%E7%AB%AF%E5%B8%B8%E7%94%A8%E5%91%BD%E4%BB%A4.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-c51e27f2").then(next)
    },
  },
  {
    path: "/Window/window终端常用命令.html",
    redirect: "/Window/window%E7%BB%88%E7%AB%AF%E5%B8%B8%E7%94%A8%E5%91%BD%E4%BB%A4.html"
  },
  {
    path: "/Window/window终端常用命令.html",
    redirect: "/Window/window%E7%BB%88%E7%AB%AF%E5%B8%B8%E7%94%A8%E5%91%BD%E4%BB%A4.html"
  },
  {
    name: "v-1af1714c",
    path: "/dev-tools/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1af1714c").then(next)
    },
  },
  {
    path: "/dev-tools/index.html",
    redirect: "/dev-tools/"
  },
  {
    name: "v-3e8e71cf",
    path: "/dev-tools/markdown.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-3e8e71cf").then(next)
    },
  },
  {
    name: "v-262c0f86",
    path: "/files.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-262c0f86").then(next)
    },
  },
  {
    name: "v-7ec674b8",
    path: "/%E4%BC%98%E8%B4%A8%E5%A5%BD%E6%96%87.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-7ec674b8").then(next)
    },
  },
  {
    path: "/优质好文.html",
    redirect: "/%E4%BC%98%E8%B4%A8%E5%A5%BD%E6%96%87.html"
  },
  {
    path: "/优质好文.html",
    redirect: "/%E4%BC%98%E8%B4%A8%E5%A5%BD%E6%96%87.html"
  },
  {
    path: '*',
    component: GlobalLayout
  }
]