/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "37.3℃",
  "description": "技术博客",
  "base": "/",
  "headTags": [
    [
      "link",
      {
        "rel": "icon",
        "href": "/images/logo.jpg"
      }
    ],
    [
      "link",
      {
        "rel": "manifest",
        "href": "/manifest.json"
      }
    ],
    [
      "meta",
      {
        "name": "theme-color",
        "content": "#3eaf7c"
      }
    ],
    [
      "meta",
      {
        "name": "apple-mobile-web-app-capable",
        "content": "yes"
      }
    ],
    [
      "meta",
      {
        "name": "apple-mobile-web-app-status-bar-style",
        "content": "black"
      }
    ],
    [
      "meta",
      {
        "name": "msapplication-TileImage",
        "content": "/images/logo.jpg"
      }
    ],
    [
      "meta",
      {
        "name": "msapplication-TileColor",
        "content": "#ffffff"
      }
    ],
    [
      "meta",
      {
        "name": "keywords",
        "content": "37.3,vue,vuepress,vuepress-theme,theme,主题,vuepress主题,blog\n    ,vuepress-blog,java,python,shell,sql,golang,script,shell script,nginx,windows,linux"
      }
    ],
    [
      "meta",
      {
        "name": "referrer",
        "content": "never"
      }
    ]
  ],
  "pages": [
    {
      "title": "Axios",
      "frontmatter": {
        "lang": "zh-CN",
        "title": "Axios",
        "description": "Axios"
      },
      "regularPath": "/Axios/Axios.html",
      "relativePath": "Axios/Axios.md",
      "key": "v-21ce7b79",
      "path": "/Axios/Axios.html",
      "headers": [
        {
          "level": 3,
          "title": "使用 Axios 拦截器来取消多次重复的请求",
          "slug": "使用-axios-拦截器来取消多次重复的请求"
        }
      ],
      "lastUpdated": "2021-11-03 09:16:36",
      "createdTime": 1635902196000
    },
    {
      "title": "Docker",
      "frontmatter": {},
      "regularPath": "/Docker/",
      "relativePath": "Docker/README.md",
      "key": "v-e8e33b10",
      "path": "/Docker/",
      "headers": [
        {
          "level": 3,
          "title": "Docker",
          "slug": "docker"
        }
      ],
      "lastUpdated": "2021-09-29 18:44:24",
      "createdTime": 1632912264000
    },
    {
      "title": "Docker",
      "frontmatter": {},
      "regularPath": "/Docker/docker.html",
      "relativePath": "Docker/docker.md",
      "key": "v-6b962f9a",
      "path": "/Docker/docker.html",
      "lastUpdated": "2021-09-29 18:44:24",
      "createdTime": 1632912264000
    },
    {
      "title": "Git SSH",
      "frontmatter": {},
      "regularPath": "/Git/Git%20SSH.html",
      "relativePath": "Git/Git SSH.md",
      "key": "v-4befb6bc",
      "path": "/Git/Git%20SSH.html",
      "headers": [
        {
          "level": 2,
          "title": "Git SSH",
          "slug": "git-ssh"
        },
        {
          "level": 3,
          "title": "生成 SSH 公钥",
          "slug": "生成-ssh-公钥"
        }
      ],
      "lastUpdated": "2021-09-29 18:44:24",
      "createdTime": 1632912264000
    },
    {
      "title": "Git SSH",
      "frontmatter": {},
      "regularPath": "/Git/Git%20%E7%BB%9F%E8%AE%A1.html",
      "relativePath": "Git/Git 统计.md",
      "key": "v-9076552c",
      "path": "/Git/Git%20%E7%BB%9F%E8%AE%A1.html",
      "headers": [
        {
          "level": 3,
          "title": "Git SSH",
          "slug": "git-ssh"
        }
      ],
      "lastUpdated": "2021-11-02 19:28:13",
      "createdTime": 1635852493000
    },
    {
      "title": "Git",
      "frontmatter": {},
      "regularPath": "/Git/",
      "relativePath": "Git/README.md",
      "key": "v-1eef2b08",
      "path": "/Git/",
      "headers": [
        {
          "level": 3,
          "title": "Git",
          "slug": "git"
        }
      ],
      "lastUpdated": "2021-09-29 18:44:24",
      "createdTime": 1632912264000
    },
    {
      "title": "gh-pages分支发布静态项目",
      "frontmatter": {},
      "regularPath": "/Git/gh-pages%E5%88%86%E6%94%AF%E5%8F%91%E5%B8%83%E9%9D%99%E6%80%81%E9%A1%B9%E7%9B%AE.html",
      "relativePath": "Git/gh-pages分支发布静态项目.md",
      "key": "v-85223540",
      "path": "/Git/gh-pages%E5%88%86%E6%94%AF%E5%8F%91%E5%B8%83%E9%9D%99%E6%80%81%E9%A1%B9%E7%9B%AE.html",
      "headers": [
        {
          "level": 3,
          "title": "gh-pages分支发布静态项目",
          "slug": "gh-pages分支发布静态项目"
        }
      ],
      "lastUpdated": "2021-09-29 18:44:24",
      "createdTime": 1632912264000
    },
    {
      "title": "Git 常见问题及解决方案",
      "frontmatter": {},
      "regularPath": "/Git/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98%E5%8F%8A%E8%A7%A3%E5%86%B3%E6%96%B9%E6%A1%88.html",
      "relativePath": "Git/常见问题及解决方案.md",
      "key": "v-c967673a",
      "path": "/Git/%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98%E5%8F%8A%E8%A7%A3%E5%86%B3%E6%96%B9%E6%A1%88.html",
      "headers": [
        {
          "level": 3,
          "title": "Git 常见问题及解决方案",
          "slug": "git-常见问题及解决方案"
        }
      ],
      "lastUpdated": "2021-09-29 18:44:24",
      "createdTime": 1632912264000
    },
    {
      "title": "Table",
      "frontmatter": {},
      "regularPath": "/HTML&&CSS/Table.html",
      "relativePath": "HTML&&CSS/Table.md",
      "key": "v-01f3148e",
      "path": "/HTML&&CSS/Table.html",
      "lastUpdated": "2021-09-29 18:44:24",
      "createdTime": 1632912264000
    },
    {
      "title": "HTML&&CSS",
      "frontmatter": {},
      "regularPath": "/HTML&&CSS/",
      "relativePath": "HTML&&CSS/README.md",
      "key": "v-ec3396a0",
      "path": "/HTML&&CSS/",
      "headers": [
        {
          "level": 3,
          "title": "HTML&&CSS",
          "slug": "html-css"
        }
      ],
      "lastUpdated": "2021-09-29 18:44:24",
      "createdTime": 1632912264000
    },
    {
      "title": "HTTP",
      "frontmatter": {},
      "regularPath": "/HTTP/",
      "relativePath": "HTTP/README.md",
      "key": "v-01bc2cf8",
      "path": "/HTTP/",
      "headers": [
        {
          "level": 3,
          "title": "HTTP",
          "slug": "http"
        }
      ],
      "lastUpdated": "2021-09-29 18:44:24",
      "createdTime": 1632912264000
    },
    {
      "title": "常见 HTTP 错误码",
      "frontmatter": {},
      "regularPath": "/HTTP/%E5%B8%B8%E8%A7%81%E9%94%99%E8%AF%AF%E7%A0%81.html",
      "relativePath": "HTTP/常见错误码.md",
      "key": "v-14236aaa",
      "path": "/HTTP/%E5%B8%B8%E8%A7%81%E9%94%99%E8%AF%AF%E7%A0%81.html",
      "headers": [
        {
          "level": 3,
          "title": "常见 HTTP 错误码",
          "slug": "常见-http-错误码"
        }
      ],
      "lastUpdated": "2021-09-29 18:44:24",
      "createdTime": 1632912264000
    },
    {
      "title": "Java 基本概念",
      "frontmatter": {},
      "regularPath": "/Java/Java%20%E5%9F%BA%E6%9C%AC%E6%A6%82%E5%BF%B5.html",
      "relativePath": "Java/Java 基本概念.md",
      "key": "v-1e07e0c5",
      "path": "/Java/Java%20%E5%9F%BA%E6%9C%AC%E6%A6%82%E5%BF%B5.html",
      "headers": [
        {
          "level": 3,
          "title": "函数与方法的区别",
          "slug": "函数与方法的区别"
        },
        {
          "level": 3,
          "title": "数据类型",
          "slug": "数据类型"
        }
      ],
      "lastUpdated": "2021-09-29 18:44:24",
      "createdTime": 1632912264000
    },
    {
      "frontmatter": {},
      "regularPath": "/Java/",
      "relativePath": "Java/README.md",
      "key": "v-8d1d9f90",
      "path": "/Java/",
      "lastUpdated": "2021-09-29 18:44:24",
      "createdTime": 1632912264000
    },
    {
      "title": "Array",
      "frontmatter": {},
      "regularPath": "/JavaScript/Array.html",
      "relativePath": "JavaScript/Array.md",
      "key": "v-008d1c5e",
      "path": "/JavaScript/Array.html",
      "headers": [
        {
          "level": 3,
          "title": "some 和 every 区别",
          "slug": "some-和-every-区别"
        }
      ],
      "lastUpdated": "2021-09-29 18:44:24",
      "createdTime": 1632912264000
    },
    {
      "title": "Browser",
      "frontmatter": {},
      "regularPath": "/JavaScript/Browser.html",
      "relativePath": "JavaScript/Browser.md",
      "key": "v-4a7d791a",
      "path": "/JavaScript/Browser.html",
      "headers": [
        {
          "level": 3,
          "title": "Browser",
          "slug": "browser"
        }
      ],
      "lastUpdated": "2021-11-02 19:28:13",
      "createdTime": 1635852493000
    },
    {
      "title": "Date",
      "frontmatter": {},
      "regularPath": "/JavaScript/Date.html",
      "relativePath": "JavaScript/Date.md",
      "key": "v-72658613",
      "path": "/JavaScript/Date.html",
      "headers": [
        {
          "level": 3,
          "title": "Date",
          "slug": "date"
        }
      ],
      "lastUpdated": "2021-11-02 19:28:13",
      "createdTime": 1635852493000
    },
    {
      "title": "ECMAScript",
      "frontmatter": {},
      "regularPath": "/JavaScript/Ecmascript.html",
      "relativePath": "JavaScript/Ecmascript.md",
      "key": "v-14c7609a",
      "path": "/JavaScript/Ecmascript.html",
      "lastUpdated": "2021-09-29 18:44:24",
      "createdTime": 1632912264000
    },
    {
      "title": "Function",
      "frontmatter": {},
      "regularPath": "/JavaScript/Function.html",
      "relativePath": "JavaScript/Function.md",
      "key": "v-6c0b1f5a",
      "path": "/JavaScript/Function.html",
      "lastUpdated": "2021-09-29 18:44:24",
      "createdTime": 1632912264000
    },
    {
      "title": "概览",
      "frontmatter": {},
      "regularPath": "/JavaScript/Introduction.html",
      "relativePath": "JavaScript/Introduction.md",
      "key": "v-f29100da",
      "path": "/JavaScript/Introduction.html",
      "headers": [
        {
          "level": 3,
          "title": "概览",
          "slug": "概览"
        }
      ],
      "lastUpdated": "2021-09-29 18:44:24",
      "createdTime": 1632912264000
    },
    {
      "title": "`JSON.stringify()`  `JSON.parse()`",
      "frontmatter": {},
      "regularPath": "/JavaScript/JSON.html",
      "relativePath": "JavaScript/JSON.md",
      "key": "v-623e0f5a",
      "path": "/JavaScript/JSON.html",
      "headers": [
        {
          "level": 3,
          "title": "`JSON.stringify()`  `JSON.parse()`",
          "slug": "json-stringify-json-parse"
        }
      ],
      "lastUpdated": "2021-09-29 18:44:24",
      "createdTime": 1632912264000
    },
    {
      "title": "JavaScript 常见设计模式",
      "frontmatter": {},
      "regularPath": "/JavaScript/Javascript%E8%AE%BE%E8%AE%A1%E6%A8%A1%E5%BC%8F.html",
      "relativePath": "JavaScript/Javascript设计模式.md",
      "key": "v-581cc044",
      "path": "/JavaScript/Javascript%E8%AE%BE%E8%AE%A1%E6%A8%A1%E5%BC%8F.html",
      "headers": [
        {
          "level": 3,
          "title": "惰性单例模式",
          "slug": "惰性单例模式"
        },
        {
          "level": 3,
          "title": "策略模式",
          "slug": "策略模式"
        },
        {
          "level": 3,
          "title": "代理模式",
          "slug": "代理模式"
        },
        {
          "level": 3,
          "title": "迭代器模式",
          "slug": "迭代器模式"
        },
        {
          "level": 3,
          "title": "发布-订阅模式（观察者模式）",
          "slug": "发布-订阅模式-观察者模式"
        },
        {
          "level": 3,
          "title": "命令模式",
          "slug": "命令模式"
        }
      ],
      "lastUpdated": "2021-09-29 18:44:24",
      "createdTime": 1632912264000
    },
    {
      "title": "Number",
      "frontmatter": {},
      "regularPath": "/JavaScript/Number.html",
      "relativePath": "JavaScript/Number.md",
      "key": "v-04e0969a",
      "path": "/JavaScript/Number.html",
      "lastUpdated": "2021-09-29 18:44:24",
      "createdTime": 1632912264000
    },
    {
      "title": "Object",
      "frontmatter": {},
      "regularPath": "/JavaScript/Object.html",
      "relativePath": "JavaScript/Object.md",
      "key": "v-e970d21a",
      "path": "/JavaScript/Object.html",
      "lastUpdated": "2021-09-29 18:44:24",
      "createdTime": 1632912264000
    },
    {
      "title": "description: 常见设计模式、数据对象、es6 知识点等",
      "frontmatter": {},
      "regularPath": "/JavaScript/",
      "relativePath": "JavaScript/README.md",
      "key": "v-12b1a550",
      "path": "/JavaScript/",
      "headers": [
        {
          "level": 2,
          "title": "description: 常见设计模式、数据对象、es6 知识点等",
          "slug": "description-常见设计模式、数据对象、es6-知识点等"
        }
      ],
      "lastUpdated": "2021-09-29 18:44:24",
      "createdTime": 1632912264000
    },
    {
      "title": "String",
      "frontmatter": {},
      "regularPath": "/JavaScript/String.html",
      "relativePath": "JavaScript/String.md",
      "key": "v-310387b3",
      "path": "/JavaScript/String.html",
      "lastUpdated": "2021-09-29 18:44:24",
      "createdTime": 1632912264000
    },
    {
      "title": "debounce   &   throttle",
      "frontmatter": {},
      "regularPath": "/JavaScript/debounce%20&%20throttle.html",
      "relativePath": "JavaScript/debounce & throttle.md",
      "key": "v-3a3cc8f2",
      "path": "/JavaScript/debounce%20&%20throttle.html",
      "headers": [
        {
          "level": 3,
          "title": "debounce   &   throttle",
          "slug": "debounce-throttle"
        }
      ],
      "lastUpdated": "2021-11-02 19:28:13",
      "createdTime": 1635852493000
    },
    {
      "title": "webpack",
      "frontmatter": {},
      "regularPath": "/JavaScript/webpack.html",
      "relativePath": "JavaScript/webpack.md",
      "key": "v-7c1162a9",
      "path": "/JavaScript/webpack.html",
      "lastUpdated": "2021-09-29 18:44:24",
      "createdTime": 1632912264000
    },
    {
      "title": "常见工具代码片段",
      "frontmatter": {},
      "regularPath": "/JavaScript/%E5%B8%B8%E8%A7%81%E5%B7%A5%E5%85%B7%E4%BB%A3%E7%A0%81%E7%89%87%E6%AE%B5.html",
      "relativePath": "JavaScript/常见工具代码片段.md",
      "key": "v-7ffca630",
      "path": "/JavaScript/%E5%B8%B8%E8%A7%81%E5%B7%A5%E5%85%B7%E4%BB%A3%E7%A0%81%E7%89%87%E6%AE%B5.html",
      "headers": [
        {
          "level": 3,
          "title": "常见工具代码片段",
          "slug": "常见工具代码片段"
        }
      ],
      "lastUpdated": "2021-11-02 19:28:13",
      "createdTime": 1632912264000
    },
    {
      "title": "常见正则表达式",
      "frontmatter": {},
      "regularPath": "/JavaScript/%E5%B8%B8%E8%A7%81%E6%AD%A3%E5%88%99%E8%A1%A8%E8%BE%BE%E5%BC%8F.html",
      "relativePath": "JavaScript/常见正则表达式.md",
      "key": "v-114baa76",
      "path": "/JavaScript/%E5%B8%B8%E8%A7%81%E6%AD%A3%E5%88%99%E8%A1%A8%E8%BE%BE%E5%BC%8F.html",
      "headers": [
        {
          "level": 3,
          "title": "常见正则表达式",
          "slug": "常见正则表达式"
        }
      ],
      "lastUpdated": "2021-09-29 18:44:24",
      "createdTime": 1632912264000
    },
    {
      "frontmatter": {},
      "regularPath": "/Linux/",
      "relativePath": "Linux/README.md",
      "key": "v-61712db8",
      "path": "/Linux/",
      "lastUpdated": "2021-09-29 18:44:24",
      "createdTime": 1632912264000
    },
    {
      "title": "Linux 常用命令",
      "frontmatter": {},
      "regularPath": "/Linux/mingling.html",
      "relativePath": "Linux/mingling.md",
      "key": "v-6395688e",
      "path": "/Linux/mingling.html",
      "headers": [
        {
          "level": 3,
          "title": "Linux 常用命令",
          "slug": "linux-常用命令"
        }
      ],
      "lastUpdated": "2021-09-29 18:44:24",
      "createdTime": 1632912264000
    },
    {
      "title": "Vim",
      "frontmatter": {},
      "regularPath": "/Linux/vim.html",
      "relativePath": "Linux/vim.md",
      "key": "v-44b3e8f9",
      "path": "/Linux/vim.html",
      "headers": [
        {
          "level": 3,
          "title": "Vim",
          "slug": "vim"
        }
      ],
      "lastUpdated": "2021-09-29 18:44:24",
      "createdTime": 1632912264000
    },
    {
      "title": "Gzip 压缩",
      "frontmatter": {},
      "regularPath": "/Nginx/Gzip%20%E5%8E%8B%E7%BC%A9.html",
      "relativePath": "Nginx/Gzip 压缩.md",
      "key": "v-7ef70638",
      "path": "/Nginx/Gzip%20%E5%8E%8B%E7%BC%A9.html",
      "headers": [
        {
          "level": 3,
          "title": "Gzip 压缩",
          "slug": "gzip-压缩"
        }
      ],
      "lastUpdated": "2021-09-29 18:44:24",
      "createdTime": 1632912264000
    },
    {
      "title": "Nginx 服务器的 Web 请求处理机制",
      "frontmatter": {},
      "regularPath": "/Nginx/Nginx%20%E6%9E%B6%E6%9E%84%E8%AE%BE%E8%AE%A1.html",
      "relativePath": "Nginx/Nginx 架构设计.md",
      "key": "v-0a101ff4",
      "path": "/Nginx/Nginx%20%E6%9E%B6%E6%9E%84%E8%AE%BE%E8%AE%A1.html",
      "headers": [
        {
          "level": 3,
          "title": "Nginx 服务器的 Web 请求处理机制",
          "slug": "nginx-服务器的-web-请求处理机制"
        }
      ],
      "lastUpdated": "2021-09-30 10:34:59",
      "createdTime": 1632912264000
    },
    {
      "frontmatter": {},
      "regularPath": "/Nginx/",
      "relativePath": "Nginx/README.md",
      "key": "v-32c3fdec",
      "path": "/Nginx/",
      "lastUpdated": "2021-09-29 18:44:24",
      "createdTime": 1632912264000
    },
    {
      "title": "Rewrite",
      "frontmatter": {},
      "regularPath": "/Nginx/Rewrite.html",
      "relativePath": "Nginx/Rewrite.md",
      "key": "v-1f7b1779",
      "path": "/Nginx/Rewrite.html",
      "headers": [
        {
          "level": 3,
          "title": "Rewrite",
          "slug": "rewrite"
        },
        {
          "level": 3,
          "title": "Rewrite 规则",
          "slug": "rewrite-规则"
        }
      ],
      "lastUpdated": "2021-09-29 18:44:24",
      "createdTime": 1632912264000
    },
    {
      "title": "Nginx 命令：",
      "frontmatter": {},
      "regularPath": "/Nginx/%E6%8C%87%E4%BB%A4%E5%8F%8A%E5%9F%BA%E6%9C%AC%E4%BB%8B%E7%BB%8D.html",
      "relativePath": "Nginx/指令及基本介绍.md",
      "key": "v-149baafb",
      "path": "/Nginx/%E6%8C%87%E4%BB%A4%E5%8F%8A%E5%9F%BA%E6%9C%AC%E4%BB%8B%E7%BB%8D.html",
      "headers": [
        {
          "level": 3,
          "title": "Nginx 命令：",
          "slug": "nginx-命令"
        },
        {
          "level": 3,
          "title": "Nginx.conf  原始配置文件",
          "slug": "nginx-conf-原始配置文件"
        }
      ],
      "lastUpdated": "2021-09-29 18:44:24",
      "createdTime": 1632912264000
    },
    {
      "title": "正向代理、反向代理",
      "frontmatter": {},
      "regularPath": "/Nginx/%E6%AD%A3%E5%90%91%E4%BB%A3%E7%90%86%E5%92%8C%E5%8F%8D%E5%90%91%E4%BB%A3%E7%90%86.html",
      "relativePath": "Nginx/正向代理和反向代理.md",
      "key": "v-4fb6e082",
      "path": "/Nginx/%E6%AD%A3%E5%90%91%E4%BB%A3%E7%90%86%E5%92%8C%E5%8F%8D%E5%90%91%E4%BB%A3%E7%90%86.html",
      "headers": [
        {
          "level": 3,
          "title": "正向代理、反向代理",
          "slug": "正向代理、反向代理"
        }
      ],
      "lastUpdated": "2021-09-29 18:44:24",
      "createdTime": 1632912264000
    },
    {
      "title": "Python",
      "frontmatter": {},
      "regularPath": "/Python/python.html",
      "relativePath": "Python/python.md",
      "key": "v-24814f9a",
      "path": "/Python/python.html",
      "lastUpdated": "2021-09-29 18:44:24",
      "createdTime": 1632912264000
    },
    {
      "frontmatter": {},
      "regularPath": "/Python/",
      "relativePath": "Python/README.md",
      "key": "v-6d1a02f8",
      "path": "/Python/",
      "lastUpdated": "2021-09-29 18:44:24",
      "createdTime": 1632912264000
    },
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "actionText": "快速上手 →",
        "actionLink": "/#命令"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-7e50d755",
      "path": "/",
      "headers": [
        {
          "level": 2,
          "title": "目录结构",
          "slug": "目录结构"
        },
        {
          "level": 2,
          "title": "命令",
          "slug": "命令"
        }
      ],
      "lastUpdated": "2021-09-30 10:34:59",
      "createdTime": 1632912264000
    },
    {
      "frontmatter": {},
      "regularPath": "/React/",
      "relativePath": "React/README.md",
      "key": "v-14b3f562",
      "path": "/React/",
      "lastUpdated": "2021-09-29 18:44:24",
      "createdTime": 1632912264000
    },
    {
      "frontmatter": {},
      "regularPath": "/React/React%20Hooks.html",
      "relativePath": "React/React Hooks.md",
      "key": "v-5aa58d88",
      "path": "/React/React%20Hooks.html",
      "lastUpdated": "2021-09-29 18:44:24",
      "createdTime": 1632912264000
    },
    {
      "title": "Route",
      "frontmatter": {},
      "regularPath": "/React/Route.html",
      "relativePath": "React/Route.md",
      "key": "v-5eda06f9",
      "path": "/React/Route.html",
      "headers": [
        {
          "level": 3,
          "title": "Route",
          "slug": "route"
        }
      ],
      "lastUpdated": "2021-09-29 18:44:24",
      "createdTime": 1632912264000
    },
    {
      "frontmatter": {},
      "regularPath": "/Window/",
      "relativePath": "Window/README.md",
      "key": "v-33ab6f10",
      "path": "/Window/",
      "lastUpdated": "2021-09-29 18:44:24",
      "createdTime": 1632912264000
    },
    {
      "title": "window 常见命令",
      "frontmatter": {},
      "regularPath": "/Window/window%E7%BB%88%E7%AB%AF%E5%B8%B8%E7%94%A8%E5%91%BD%E4%BB%A4.html",
      "relativePath": "Window/window终端常用命令.md",
      "key": "v-c51e27f2",
      "path": "/Window/window%E7%BB%88%E7%AB%AF%E5%B8%B8%E7%94%A8%E5%91%BD%E4%BB%A4.html",
      "headers": [
        {
          "level": 2,
          "title": "window 常见命令",
          "slug": "window-常见命令"
        }
      ],
      "lastUpdated": "2021-09-29 18:44:24",
      "createdTime": 1632912264000
    },
    {
      "title": "Dev Tools",
      "frontmatter": {},
      "regularPath": "/dev-tools/",
      "relativePath": "dev-tools/README.md",
      "key": "v-1af1714c",
      "path": "/dev-tools/",
      "lastUpdated": "2021-09-29 18:44:24",
      "createdTime": 1632912264000
    },
    {
      "title": "Markdown",
      "frontmatter": {},
      "regularPath": "/dev-tools/markdown.html",
      "relativePath": "dev-tools/markdown.md",
      "key": "v-3e8e71cf",
      "path": "/dev-tools/markdown.html",
      "lastUpdated": "2021-09-29 18:44:24",
      "createdTime": 1632912264000
    },
    {
      "title": "文件",
      "frontmatter": {},
      "regularPath": "/files.html",
      "relativePath": "files.md",
      "key": "v-262c0f86",
      "path": "/files.html",
      "lastUpdated": "2021-09-29 18:44:24",
      "createdTime": 1632912264000
    },
    {
      "title": "优质文章",
      "frontmatter": {},
      "regularPath": "/%E4%BC%98%E8%B4%A8%E5%A5%BD%E6%96%87.html",
      "relativePath": "优质好文.md",
      "key": "v-7ec674b8",
      "path": "/%E4%BC%98%E8%B4%A8%E5%A5%BD%E6%96%87.html",
      "headers": [
        {
          "level": 3,
          "title": "优质文章",
          "slug": "优质文章"
        }
      ],
      "lastUpdated": "2021-09-29 18:44:24",
      "createdTime": 1632912264000
    }
  ],
  "themeConfig": {
    "repo": "vuejs/vuepress",
    "editLinks": true,
    "docsDir": "/",
    "logo": "./public/images/logo.jpg",
    "nav": [
      {
        "text": "Axios",
        "link": "/Axios/"
      },
      {
        "text": "Docker",
        "link": "/Docker/"
      },
      {
        "text": "Git",
        "link": "/Git/"
      },
      {
        "text": "HTML&&CSS",
        "link": "/HTML&&CSS/"
      },
      {
        "text": "HTTP",
        "link": "/HTTP/"
      },
      {
        "text": "Java",
        "link": "/Java/"
      },
      {
        "text": "JavaScript",
        "link": "/JavaScript/"
      },
      {
        "text": "Linux",
        "link": "/Linux/"
      },
      {
        "text": "Nginx",
        "link": "/Nginx/"
      },
      {
        "text": "Python",
        "link": "/Python/"
      },
      {
        "text": "React",
        "link": "/React/"
      },
      {
        "text": "Window",
        "link": "/Window/"
      },
      {
        "text": "dev-tools",
        "link": "/dev-tools/"
      }
    ],
    "sidebar": {
      "/docs/": [
        {
          "title": "Axios",
          "children": [
            "undefined/Axios/Axios"
          ]
        },
        {
          "title": "Docker",
          "children": [
            "undefined/Docker/",
            "undefined/Docker/docker"
          ]
        },
        {
          "title": "Git",
          "children": [
            "undefined/Git/Git SSH",
            "undefined/Git/Git 统计",
            "undefined/Git/",
            "undefined/Git/gh-pages分支发布静态项目",
            "undefined/Git/常见问题及解决方案"
          ]
        },
        {
          "title": "HTML&&CSS",
          "children": [
            "undefined/HTML&&CSS/",
            "undefined/HTML&&CSS/Table"
          ]
        },
        {
          "title": "HTTP",
          "children": [
            "undefined/HTTP/",
            "undefined/HTTP/常见错误码"
          ]
        },
        {
          "title": "Java",
          "children": [
            "undefined/Java/Java 基本概念",
            "undefined/Java/"
          ]
        },
        {
          "title": "JavaScript",
          "children": [
            "undefined/JavaScript/Array",
            "undefined/JavaScript/Browser",
            "undefined/JavaScript/Date",
            "undefined/JavaScript/Ecmascript",
            "undefined/JavaScript/Function",
            "undefined/JavaScript/Introduction",
            "undefined/JavaScript/JSON",
            "undefined/JavaScript/Javascript设计模式",
            "undefined/JavaScript/Number",
            "undefined/JavaScript/Object",
            "undefined/JavaScript/",
            "undefined/JavaScript/String",
            "undefined/JavaScript/debounce & throttle",
            "undefined/JavaScript/webpack",
            "undefined/JavaScript/常见工具代码片段",
            "undefined/JavaScript/常见正则表达式"
          ]
        },
        {
          "title": "Linux",
          "children": [
            "undefined/Linux/",
            "undefined/Linux/mingling",
            "undefined/Linux/vim"
          ]
        },
        {
          "title": "Nginx",
          "children": [
            "undefined/Nginx/Gzip 压缩",
            "undefined/Nginx/Nginx 架构设计",
            "undefined/Nginx/",
            "undefined/Nginx/Rewrite",
            {
              "title": "images",
              "children": [],
              "parent": "Nginx"
            },
            "undefined/Nginx/指令及基本介绍",
            "undefined/Nginx/正向代理和反向代理"
          ]
        },
        {
          "title": "Python",
          "children": [
            "undefined/Python/",
            "undefined/Python/python"
          ]
        },
        "",
        {
          "title": "React",
          "children": [
            "undefined/React/",
            "undefined/React/React Hooks",
            "undefined/React/Route"
          ]
        },
        {
          "title": "Window",
          "children": [
            "undefined/Window/",
            "undefined/Window/window终端常用命令"
          ]
        },
        {
          "title": "dev-tools",
          "children": [
            "undefined/dev-tools/",
            "undefined/dev-tools/markdown"
          ]
        },
        "files",
        "优质好文"
      ],
      "/": []
    },
    "lastUpdated": "上次更新",
    "author": "37.3℃"
  }
}